dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  shared_preferences: ^2.2.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  intl: ^0.18.1
