// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrgZ4lP5eKL-ZVydNtQ64phe1jHzUwL0',
    appId: '1:496458196556:web:bb454a56cbdae6fbf936e9',
    messagingSenderId: '496458196556',
    projectId: 'calendarapp-b181d',
    authDomain: 'calendarapp-b181d.firebaseapp.com',
    storageBucket: 'calendarapp-b181d.firebasestorage.app',
    measurementId: 'G-09VQCCC2SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeiaWfx_Gfv9Rqkq3RXP9SiTPdHK0Kf7U',
    appId: '1:496458196556:android:08b104b48d7a7fc9f936e9',
    messagingSenderId: '496458196556',
    projectId: 'calendarapp-b181d',
    storageBucket: 'calendarapp-b181d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ4pifXSRgqG8BMC-KfOk7XcIorTkv-Mc',
    appId: '1:496458196556:ios:ae43a6c269a57804f936e9',
    messagingSenderId: '496458196556',
    projectId: 'calendarapp-b181d',
    storageBucket: 'calendarapp-b181d.firebasestorage.app',
    iosClientId: '496458196556-8hc9seqjh3pugmbeghmkn6872cmvi3a3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
